apiVersion: image.toolkit.fluxcd.io/v1beta1
kind: ImagePolicy
metadata:
  name: addresses
  namespace: flux-system
spec:
  imageRepositoryRef:
    name: addresses
  filterTags:
    pattern: '^develop-(?P<version>([0-9]|[1-9][0-9]*)\.([0-9]|[1-9][0-9]*)\.([0-9]|[1-9][0-9]*)(?:-alpha([0-9]+)))[-[0-9a-f]+]?'
    extract: '$version'
  policy:
    numerical:
      order: asc